import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { AgUiProvider } from "../components/ag-ui/AgUiProvider";
import { AppShell } from "../components/AppShell";
import { DashboardContextProvider } from "../contexts/DashboardContext";

const sansFont = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const monoFont = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const runtimeUrl =
    process.env.NEXT_PUBLIC_AG_UI_RUNTIME_URL || "http://localhost:8004/ag-ui/run";

  return (
    <html lang="en">
      <body className={`${sansFont.variable} ${monoFont.variable} antialiased`}>
        <DashboardContextProvider>
          <AgUiProvider runtimeUrl={runtimeUrl}>
            <AppShell>{children}</AppShell>
          </AgUiProvider>
        </DashboardContextProvider>
      </body>
    </html>
  );
}
