import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AgUiProvider } from "../components/ag-ui/AgUiProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const runtimeUrl =
    process.env.NEXT_PUBLIC_AG_UI_RUNTIME_URL || "http://localhost:8004/ag-ui/run";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AgUiProvider runtimeUrl={runtimeUrl}>
          {children}
        </AgUiProvider>
      </body>
    </html>
  );
}
